// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNSPECIFIED Status = 0
	Status_EXECUTED    Status = 1
	Status_FAILED      Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "EXECUTED",
		2: "FAILED",
	}
	Status_value = map[string]int32{
		"UNSPECIFIED": 0,
		"EXECUTED":    1,
		"FAILED":      2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_worker_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_worker_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

type ExecuteStageRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	StageRunId    string                 `protobuf:"bytes,2,opt,name=stage_run_id,json=stageRunId,proto3" json:"stage_run_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	StageConfig   string                 `protobuf:"bytes,5,opt,name=stage_config,json=stageConfig,proto3" json:"stage_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStageRunRequest) Reset() {
	*x = ExecuteStageRunRequest{}
	mi := &file_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStageRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStageRunRequest) ProtoMessage() {}

func (x *ExecuteStageRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStageRunRequest.ProtoReflect.Descriptor instead.
func (*ExecuteStageRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteStageRunRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *ExecuteStageRunRequest) GetStageRunId() string {
	if x != nil {
		return x.StageRunId
	}
	return ""
}

func (x *ExecuteStageRunRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteStageRunRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ExecuteStageRunRequest) GetStageConfig() string {
	if x != nil {
		return x.StageConfig
	}
	return ""
}

type ExecuteStageRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Outputs       map[string]string      `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStageRunResponse) Reset() {
	*x = ExecuteStageRunResponse{}
	mi := &file_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStageRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStageRunResponse) ProtoMessage() {}

func (x *ExecuteStageRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStageRunResponse.ProtoReflect.Descriptor instead.
func (*ExecuteStageRunResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteStageRunResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNSPECIFIED
}

func (x *ExecuteStageRunResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteStageRunResponse) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_proto_worker_proto protoreflect.FileDescriptor

const file_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/worker.proto\x12\x05proto\"\xa6\x01\n" +
	"\x16ExecuteStageRunRequest\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12 \n" +
	"\fstage_run_id\x18\x02 \x01(\tR\n" +
	"stageRunId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12!\n" +
	"\fstage_config\x18\x05 \x01(\tR\vstageConfig\"\xd9\x01\n" +
	"\x17ExecuteStageRunResponse\x12%\n" +
	"\x06status\x18\x01 \x01(\x0e2\r.proto.StatusR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12E\n" +
	"\aoutputs\x18\x03 \x03(\v2+.proto.ExecuteStageRunResponse.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*3\n" +
	"\x06Status\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\f\n" +
	"\bEXECUTED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x022a\n" +
	"\rWorkerService\x12P\n" +
	"\x0fExecuteStageRun\x12\x1d.proto.ExecuteStageRunRequest\x1a\x1e.proto.ExecuteStageRunResponseB\x1cZ\x1atorv.io/worker-agent/protob\x06proto3"

var (
	file_proto_worker_proto_rawDescOnce sync.Once
	file_proto_worker_proto_rawDescData []byte
)

func file_proto_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)))
	})
	return file_proto_worker_proto_rawDescData
}

var file_proto_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_worker_proto_goTypes = []any{
	(Status)(0),                     // 0: proto.Status
	(*ExecuteStageRunRequest)(nil),  // 1: proto.ExecuteStageRunRequest
	(*ExecuteStageRunResponse)(nil), // 2: proto.ExecuteStageRunResponse
	nil,                             // 3: proto.ExecuteStageRunResponse.OutputsEntry
}
var file_proto_worker_proto_depIdxs = []int32{
	0, // 0: proto.ExecuteStageRunResponse.status:type_name -> proto.Status
	3, // 1: proto.ExecuteStageRunResponse.outputs:type_name -> proto.ExecuteStageRunResponse.OutputsEntry
	1, // 2: proto.WorkerService.ExecuteStageRun:input_type -> proto.ExecuteStageRunRequest
	2, // 3: proto.WorkerService.ExecuteStageRun:output_type -> proto.ExecuteStageRunResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_worker_proto_init() }
func file_proto_worker_proto_init() {
	if File_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_proto_depIdxs,
		EnumInfos:         file_proto_worker_proto_enumTypes,
		MessageInfos:      file_proto_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_proto = out.File
	file_proto_worker_proto_goTypes = nil
	file_proto_worker_proto_depIdxs = nil
}
